#!/usr/bin/env php

<?php

use Acme\ShowComand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

require __DIR__ . '/src/constants.php';
require __DIR__ . '/src/functions.php';
loadDotEnv('.env');

$app = new Application('Moviepedia', '1.0');

$app->add(new ShowComand);

$app->run();